config/routes.rb
Rails.application.routes.draw do

  # 管理者用devise
  devise_for :admin,skip: [:registrations,:passwords], controllers: {
  sessions: "admin/sessions"
  }
  # ユーザー用devise
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # 管理者
  namespace :admin do
    get '/' => 'homes#top'
    resources :post_images, only: [:show, :index, :edit, :update, :destroy]
    resources :users, only: [:show, :index,:edit,:update]
    resources :news_images, only: [:new,:create, :index, :edit, :update ]
  end
  # 検索
  get "search" => "searches#search"
  # ユーザー(ファイル構成違うため、module)
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about' , as: 'about'
    get 'relationships/followings'
    get 'relationships/followers'
    get "users/:id/following" => "users#following" ,as:"following"
    get "users/:id/follower" => "users#follower" ,as:"follower"

    resources :users, only: [:show, :index, :edit, :update] do
      post 'follow/:id' => 'relations#create', as: 'follow'
      post 'unfollow/:id' => 'relations#destroy', as: 'unfollow'
      # users/:id/favorites というルーティング
      member do
        get :favorites
      end
    end
    # ハッシュ
    get '/post_images/hashtag/:name' => 'post_images#hashtag'

    resources :post_images, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get :following_posts
        get :popular
      end
    end
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

 before_action :side_view, only: [ :search ]
 before_action :login_check, only: [ :search ]

  def search
    @method = params[:method]
    @word = params[:word]
    @search = params[:search]
      if @method == "「投稿」からさがす"
         @post_images = PostImage.search_for(@word,@search)
      else
         @users = User.search_for(@word,@search)
      end
  end

    private
    
    def side_view
      @post_categories = PostCategory.all
      @hashtags = Hashtag.all.to_a.group_by{ |hashtag| hashtag.post_images.count}
    end

      # ログインの確認
    def login_check
      unless signed_in?
        redirect_to root_path
      end
    end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searches/search.html.erb
<!--searchから遷移-->

<div class="container-fluid">
  <div class="row mx-5 mt-5">
    <div class="col-md-12">
      <div class='row mx-3 justify-content-start'>

        <div class="col-md-12">
          <!--検索部分-->
          <p>ハッシュタグ一覧</p>
            <div class="row">
              <div class= "col-xs-12 col-lg-12 col-md-12 col-sm-12">
                <div class= "hashtag-name">
                  <% @hashtags.sort.reverse.each do |count| %>
                    <% count[1].each do |hashtag| %>
                     <%= link_to "##{hashtag.hashname}(#{hashtag.post_images.count})","/post_images/hashtag/#{hashtag.hashname}",date:{"turbolinks"=>false}, class: 'text-info' %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>

          <div class="row">
            <div class= "col-xs-12 col-lg-12 col-md-12 col-sm-12">
              <%= form_with url: search_path, local: true, method: :get do |s| %>
               <div class="form-group row mx-auto">
                  <%= s.label'フリーワード' %>
                  <%= s.text_field :word, class: 'form-control mb-2', placeholder:"ワード検索"%>
                  <%= s.label'絞り込み' %>
                  <%= s.select :method, options_for_select([['「投稿」からさがす'],['「ユーザー」からさがす']]),{ prompt: '-' },class: "form-control" %>
                  <%= s.select :search, options_for_select({"完全一致"=>"perfect_match", "前方一致"=>"forward_match",  "後方一致"=>"backward_match", "部分一致"=>"partial_match"}),{ prompt: '-' },class: "form-control" %>
               </div>
                <div class="form-group row mx-auto">
                  <%= button_tag type: :submit,class: "btn btn-outline-info form-control" do %>
                    <i class="fa-solid fa-magnifying-glass"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
          <h3>検索結果</h3>
        </div>

          <!--投稿で検索-->
         <% if @method == "「投稿」からさがす" %>
            <% if @post_images.present? %>
              <div class="image-warp d-flex flex-reverse">
                <% @post_images.each do |image| %>
                <div class="my-4">
                  <div class="card border-success shadow p-3 mx-3" style="width:23rem">
                    <div class= "mx-auto">
                      <div class="mt-1 pt-3 pl-3 mb-2">
                        <!--アイコン-->
                        <%= link_to user_path(image.user),class:"text-dark" do %>
                        <%= image_tag image.user.get_profile_image(130,130),class: "rounded-circle icon" %>
                        <%= image.user.name %>
                        <% end %>
                      </div>
                      <div class= "index-image col-md-11">
                        <!--写真-->
                        <%= image_tag image.get_image(700,520), class: "img-fluid" %>
                      </div>
                      <p class="font-weight-bold card-title pl-3 pt-2 col-md-11">
                        <!--タイトル-->
                        <%= link_to post_image_path(image.id), class:"text-dark" do %>
                        <%= image.title %>
                        <% end %>
                      </p>
                      <p class=" pl-3 pt-2 col-md-11">
                        <!--内容,ハッシュタグリンク-->
                        <%= render_with_hashtags(image.body) %><br>
                        <%= image.created_at.strftime('%Y/%m/%d') %>
                        ♥<%= image.favorites.count %>
                      <i class="fa-regular fa-message"></i><%= image.comments.count %>
                      </p>
                      <h2 class="text-right favorite-btn_<%= image.id %>">
                        <%= render "public/favorites/favorite-btn", post_image: image %>
                      </h2>
                    </div>
                  </div>
                </div>
                <% end %>
              </div>
            <% else %>
            <!--いない場合は非表示-->
            <% end %>
         <!--ユーザで検索ー-->
         <% else %>
          <% if @users.present? %>
            <table class='table table-inverse col-md-10 mx-auto table-bordered bg-light'>
              <thead>
                <tr>
                 <th>image</th>
                 <th>name</th>
                 <th colspan="4"></th>
                </tr>
              </thead>
              <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                   <%= image_tag user.get_profile_image(200,200),class: "rounded-circle user" %>
                  </td>
                  <td class="font-weight-bold ">
                    <%= link_to user_path(user.id), class:"text-dark"  do %>
                     <%= user.name %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to user_path(user.id), class:"text-dark" do %>
                      show
                    <% end %>
                  </td>
                  <td>
                    <% if current_user.following?(user) %>
                      <p>
                        <%= link_to 'フォロー中', user_unfollow_path(current_user, user), method: :POST, class:"text-dark" %>
                      </p>
                    <% else %>
                      <p>
                        <%= link_to 'フォローする', user_follow_path(current_user, user), method: :POST, class:"text-dark" %>
                      </p>
                    <% end %>
                 </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          <% else %>
          <!--いない場合は非表示-->
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>