config/routes.rb
Rails.application.routes.draw do

  # 管理者用devise
  devise_for :admin,skip: [:registrations,:passwords], controllers: {
  sessions: "admin/sessions"
  }
  # ユーザー用devise
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # 管理者
  namespace :admin do
    get '/' => 'homes#top'
    resources :post_images, only: [:show, :index, :edit, :update, :destroy]
    resources :users, only: [:show, :index,:edit,:update]
    resources :news_images, only: [:new,:create, :index, :edit, :update ]
  end
  # 検索
  get "search" => "searches#search"
  # ユーザー(ファイル構成違うため、module)
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about' , as: 'about'
    get 'relationships/followings'
    get 'relationships/followers'
    get "users/:id/following" => "users#following" ,as:"following"
    get "users/:id/follower" => "users#follower" ,as:"follower"

    resources :users, only: [:show, :index, :edit, :update] do
      post 'follow/:id' => 'relations#create', as: 'follow'
      post 'unfollow/:id' => 'relations#destroy', as: 'unfollow'
      # users/:id/favorites というルーティング
      member do
        get :favorites
      end
    end
    # ハッシュ
    get '/post_images/hashtag/:name' => 'post_images#hashtag'

    resources :post_images, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get :following_posts
        get :popular
      end
    end
  end

end

app/models/post_image.rb
class PostImage < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :post_category
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_image_hashtag_relations, dependent: :destroy
  has_many :hashtags, through: :post_image_hashtag_relations
  has_many :favorite_users, through: :favorites, source: :user

  # 画像
  has_one_attached :image

  # 画像確認/サイズ
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-post_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-post_image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  # いいねしているユーザーがいるかどうか
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  #DBへのコミット直前に実施する
  after_create do
    post_image = PostImage.find_by(id:id)
    hashtags  = body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    post_image.hashtags = []
    hashtags.uniq.map do |hashtag|
      #ハッシュタグは先頭の'#'を外した上で保存
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      post_image.hashtags << tag
    end
  end

  before_update do
    post_image = PostImage.find_by(id:id)
    post_image.hashtags.clear
    hashtags = body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      post_image.hashtags << tag
    end
  end

  # 検索
  def self.search_for(word, search)
    if search == "perfect_match"
      PostImage.where(title:word)
    elsif search == "forward_match"
      PostImage.where('title LIKE?',word+'%')
    elsif search == "backward_match"
      PostImage.where('title LIKE?','%'+word)
    elsif search == "partial_match"
      PostImage.where('title LIKE?','%'+word+'%')
    else
      # 表示しない
    end
  end


  validates :title, presence: true
  validates :body, presence: true
  validates :post_category, presence: true
end

app/controllers/admin/post_images_controller.rb
class Admin::PostImagesController < ApplicationController
 before_action :authenticate_admin!, only: [:show,:new, :index, :edit, :hashtag]
 before_action :side_view, only: [:index, :show, :edit, :hashtag,:update ]
 before_action :login_check, only: [:index, :show, :edit, :hashtag]

  # 投稿一覧
  def index
    @post_images = params[:post_category].present? ? PostCategory.find(params[:post_category]).post_images: PostImage.all
    @hashtags = Hashtag.all.to_a.group_by{ |hashtag| hashtag.post_images.count}
  end

  # 投稿詳細
  def show
    @post_image = PostImage.find(params[:id])
    @user = @post_image.user
    @comment = Comment.new
  end

  # 投稿編集
  def edit
    @post_image = PostImage.find(params[:id])
  end

  # 投稿更新
  def update
    @post_image = PostImage.find(params[:id])
    if @post_image.update(post_image_params)
       redirect_to admin_post_images_path, notice: '更新に成功しました'
    else
      render:edit
    end
  end
  # 投稿削除
  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to admin_post_images_path
  end

  # ハッシュ
  def hashtag
    @user = current_user
    if params[:name].nil?
      @hashtags = Hashtag.all.to_a.group_by{ |hashtag| hashtag.post_images.count}
    else
      @hashtag = Hashtag.find_by(hashname: params[:name])
      @post_image = @hashtag.post_images.reverse_order
      @hashtags = Hashtag.all.to_a.group_by{ |hashtag| hashtag.post_images.count}
      @post_images = @hashtag.post_images.all
    end
  end

  private

  def post_image_params
    params.require(:post_image).permit(:title, :image, :body, :hashbody, :user_id, :post_category_id)
  end

  def side_view
    @post_categories = PostCategory.all
    @hashtags = Hashtag.all.to_a.group_by{ |hashtag| hashtag.post_images.count}
  end

  def login_check
    unless signed_in?
    redirect_to root_path
    end
  end

end

app/helpers/admin/post_images_helper.rb
module Admin::PostImagesHelper
end

app/views/admin/post_images/edit.html.erb
<!--投稿編集-->
<div class="container mt-5">
  <div class="row mx-auto mt-5 justify-content-center">
    <div class="col-md-8 card shadow p-3">

    <div  class="row mb-2 pl-5 card-body">
       <%= link_to admin_post_image_path(@post_image),class:"text-info" do %>
          <h2>
           <i class="fa-solid fa-circle-left"></i>
          </h2>
       <% end %>
      </div>
     <!--エラーメッセージ-->
     <%= render 'layouts/error',object: @post_image %>
    <!--フォーム-->
    <%= form_with model: @post_image, url:admin_post_image_path ,method: :patch do |f| %>
      <div class="form-group col-md-11 px-5 pb-5 mx-auto">
       <%= f.file_field :image , accept: "image/*", class: "w-100 mb-2"%>
       <%= f.text_field :title , class: 'form-control mb-2'%>
       <%= f.collection_select :post_category_id, PostCategory.all, :id, :post_category, { prompt: 'カテゴリー選択' }, class: 'form-control mb-2' %>
       <%= f.text_area :body , class: 'form-control mb-2'%>
       <%= f.submit '編集',class: "btn btn-lg btn-block btn-outline-info mt-4 my-sm-0" %>
      </div>

     </div>
    <% end %>
   </div>
  </div>
</div>

app/views/admin/post_images/index.html.erb
<!--投稿一覧-->
<div class="container-fluid">
 <div class="row mx-5 mt-5">
  <div class="col-md-12">

    <p class="ml-3 mt-3">
    新規投稿順で表示
    </p>
     <div class="image-warp d-flex flex-reverse">
       <% @post_images.each do |post_image| %>
        <div class="my-4">
          <div class="card border-success shadow p-3 mx-3" style="width:23rem">
            <div class= "mx-auto">

             <div class="mt-1 pt-3 pl-3">
               <!--アイコン-->
               <%= image_tag post_image.user.get_profile_image(130,130), class: "icon rounded-circle mb-3" %>
               <%= link_to admin_user_path(post_image.user), class:"text-dark" do %>
                 <%= post_image.user.name %>
               <% end %>
             </div>

             <div class="index-image col-md-11">
               <%= image_tag post_image.get_image(700,520), class: "img-fluid"%>
             </div>

             <!--文章-->
             <p class="font-weight-bold card-title pl-3 pt-2 col-md-11">
              <%= link_to admin_post_image_path(post_image.id), class:"text-dark" do %>
                <%= post_image.title %>
              <% end %>
                ♥<%= post_image.favorites.count %>
               <i class="fa-regular fa-message"></i><%= post_image.comments.count %>
             </p>
             <p class="card-title pl-3 pt-2 col-md-11">
               <%= post_image.body %>
               <%= post_image.created_at.strftime('%Y/%m/%d') %>
             </p>

            </div>
          </div>
        </div>
       <% end %>
      </div>

   </div>
 </div>
</div>

app/views/admin/post_images/show.html.erb
<!--投稿詳細-->
<div class="container mt-5">
  <div class="row mx-5 mt-5">
    <div class="col-md-12">

     <div class="card border-success shadow p-3 mx-auto mt-5" style="width:50rem">
      <div class='row no-gutters mx-auto'>


         <div class="col-md-8">
            <%= link_to(admin_user_path(@post_image.user), class:"text-dark") do %>
                <%= image_tag @post_image.user.get_profile_image(30,30),class: " icon rounded-circle" %>
                <%= @post_image.user.name %>
            <% end %>
            <!--管理者がサインインしてる場合は編集/削除ができる-->
            <%= link_to edit_admin_post_image_path(@post_image) do %>
              編集
            <% end %>|
            <%= link_to admin_post_images_path, method: :delete, data: { confirm: '本当に消しますか？' } do%>
              削除
            <% end %>

            <div class="show-image mt-2">
              <%= image_tag @post_image.get_image(700,520), class: "img-fluid" %>
            </div>
          </div>

          <div class="col-md-4">
            <div class="card-body">

              <p class="font-weight-bold">
                <%= @post_image.title %>
              </p>
              <p>
                <%= @post_image.body %>
              </p>
              <p>
                ♥<%= @post_image.favorites.count %>
                <i class="fa-regular fa-message"></i><%= @post_image.comments.count %>
              </p>

              <h5 class="font-weight-normal">
                <i class="fa-regular fa-message"></i><%= @post_image.comments.count %>
              </h5>

            <!--コメント一覧-->
            <% @post_image.comments.each do |comment| %>

              <%= image_tag comment.user.get_profile_image(30,30),class: "icon rounded-circle"%>
                <%= link_to(admin_user_path(comment.user), class:"text-dark") do %>
                 <%= comment.user.name %>
                <% end %>

              <%= comment.created_at.strftime('%Y/%m/%d') %><br>
              <%= comment.comment %>
              <%= link_to "削除", post_image_comment_path(comment.post_image, comment), method: :delete %>
            <% end %>
           </div>

         </div>
        </div>

    </div>
  </div>
</div>