config/routes.rb
Rails.application.routes.draw do

  # 管理者用devise
  devise_for :admin,skip: [:registrations,:passwords], controllers: {
  sessions: "admin/sessions"
  }
  # ユーザー用devise
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # 管理者
  namespace :admin do
    get '/' => 'homes#top'
    resources :post_images, only: [:show, :index, :edit, :update, :destroy]
    resources :users, only: [:show, :index,:edit,:update]
    resources :news_images, only: [:new,:create, :index, :edit, :update ]
  end
  # 検索
  get "search" => "searches#search"
  # ユーザー(ファイル構成違うため、module)
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about' , as: 'about'
    get 'relationships/followings'
    get 'relationships/followers'
    get "users/:id/following" => "users#following" ,as:"following"
    get "users/:id/follower" => "users#follower" ,as:"follower"

    resources :users, only: [:show, :index, :edit, :update] do
      post 'follow/:id' => 'relations#create', as: 'follow'
      post 'unfollow/:id' => 'relations#destroy', as: 'unfollow'
      # users/:id/favorites というルーティング
      member do
        get :favorites
      end
    end
    # ハッシュ
    get '/post_images/hashtag/:name' => 'post_images#hashtag'

    resources :post_images, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get :following_posts
        get :popular
      end
    end
  end

end

app/models/news_image.rb
class NewsImage < ApplicationRecord
 # 画像
  has_one_attached :news_image

  # 画像確認/サイズ
  def news_get_image(width, height)
    unless news_image.attached?
      file_path = Rails.root.join('app/assets/images/no-post_image.jpg')

      news_image.attach(io: File.open(file_path), filename: 'no-post_image.jpg', content_type: 'image/jpg')

    end
    news_image.variant(resize_to_limit: [width, height]).processed
  end
  validates :news_title, presence: true
  validates :news_body, presence: true
end

app/controllers/admin/news_images_controller.rb
class Admin::NewsImagesController < ApplicationController

  before_action :login_check, only: [:index, :show, :edit, :new]

  # 新規
  def new
  @news_image = NewsImage.new
  end

  # 作成
  def create
   @news_image = NewsImage.new(news_image_params)
    if @news_image.save
       redirect_to admin_news_images_path, notice: '投稿に成功しました'
    else
       render:new
    end
  end

  # 詳細
  def index
    @news_images = NewsImage.all.order(created_at: :desc)
  end

  # 投稿編集
  def edit
    @news_image = NewsImage.find(params[:id])
  end

  # 投稿更新
  def update
    @news_image = NewsImage.find(params[:id])
     if @news_image.update(news_image_params)
       redirect_to admin_news_images_path, notice: '更新に成功しました'
     else
       render:edit
     end
  end

  private

  # 許可
  def news_image_params
    params.require(:news_image).permit(:news_title, :news_image, :news_body, :admin_id)
  end

  # ログインしているかどうか
  def login_check
    unless signed_in?
    redirect_to root_path
    end
  end

end

app/views/admin/news_images/edit.html.erb
<!--お知らせ編集-->
<div class="container mt-5">
  <div class="row mt-5 mx-auto justify-content-center">
    <div class="col-md-8 card shadow p-3">

      <div  class="row mb-2 pl-5 card-body">
       <%= link_to admin_news_images_path,class:"text-info" do %>
          <h2>
           <i class="fa-solid fa-circle-left"></i>
          </h2>
       <% end %>
      </div>

     <!--エラーメッセージ-->
     <%= render 'layouts/error',object: @news_image %>

   <%= form_with model: @news_image, url: admin_news_image_path ,method: :patch do |f| %>
    <div class="form-group col-md-11 px-5 pb-5 mx-auto">
      <%= f.file_field :news_image, accept: "image/*", class: "w-100 mb-2" %>
      <%= f.text_field :news_title , class: 'form-control mb-2'%>
      <%= f.text_area :news_body , class: 'form-control mb-2'%>
      <%= f.submit '編集',class: "btn btn-lg btn-block btn-outline-info mt-4 my-sm-0" %>
    </div>
  <% end %>
  </div>
</div>

app/views/admin/news_images/index.html.erb
<!--お知らせ一覧-->
<div class="container mt-5">
  <div class="row mx-5 mt-5">
    <div class="col-md-12">

      <% @news_images.each do |news_image| %>
        <div class="card border-success shadow p-3 mx-auto mt-5" style="width:50rem">
          <div class='row no-gutters'>

              <div class="col-md-8">
                <%= news_image.created_at.strftime('%Y/%m/%d') %>更新
                  <% if admin_signed_in? %>
                    <!--管理者がサインインしてる場合は編集/削除ができる-->
                    <%= link_to edit_admin_news_image_path(news_image) do %>
                      編集
                    <% end %>
                  <% end %>
                  <div class= "show-image mt-2">
                  <%= image_tag news_image.news_get_image(700,520), class: "img-fluid" %>
                  </div>
              </div>

              <div class="col-md-4">
                <div class="card-body">
                  <p class="font-weight-bold">
                    <%= news_image.news_title %>
                  </p>
                  <p>
                    <%= news_image.news_body %>
                  </p>
                </div>
              </div>
          </div>
        </div>
    　<% end %>

   </div>
  </div>
</div>

app/views/admin/news_images/new.html.erb
<!--お知らせ新規-->
<div class="container mt-5">
  <div class="row mt-5 mx-auto justify-content-center">
    <div class="col-md-8 card shadow p-3">

      <div  class="row mb-2 pl-5 card-body">
       <%= link_to admin_news_images_path,class:"text-info" do %>
          <h2>
           <i class="fa-solid fa-circle-left"></i>
          </h2>
       <% end %>
      </div>
     <!--エラーメッセージ-->
     <%= render 'layouts/error',object: @news_image %>
     <!--フォーム-->
     <%= form_with model: @news_image, url: admin_news_images_path  do |f| %>
      <div class="form-group col-md-11 px-5 pb-5 mx-auto">
        <%= f.file_field :news_image, accept: "image/*", class: "w-100 mb-2" %>
        <%= f.text_field :news_title , class: 'form-control mb-2'%>
        <%= f.text_area :news_body , class: 'form-control mb-2'%>
        <%= f.submit '投稿',class: "btn btn-lg btn-block btn-outline-info mt-4 my-sm-0" %>
      </div>
     <% end %>
  </div>
</div>