config/routes.rb
Rails.application.routes.draw do

  # 管理者用devise
  devise_for :admin,skip: [:registrations,:passwords], controllers: {
  sessions: "admin/sessions"
  }
  # ユーザー用devise
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # 管理者
  namespace :admin do
    get '/' => 'homes#top'
    resources :post_images, only: [:show, :index, :edit, :update, :destroy]
    resources :users, only: [:show, :index,:edit,:update]
    resources :news_images, only: [:new,:create, :index, :edit, :update ]
  end
  # 検索
  get "search" => "searches#search"
  # ユーザー(ファイル構成違うため、module)
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about' , as: 'about'
    get 'relationships/followings'
    get 'relationships/followers'
    get "users/:id/following" => "users#following" ,as:"following"
    get "users/:id/follower" => "users#follower" ,as:"follower"

    resources :users, only: [:show, :index, :edit, :update] do
      post 'follow/:id' => 'relations#create', as: 'follow'
      post 'unfollow/:id' => 'relations#destroy', as: 'unfollow'
      # users/:id/favorites というルーティング
      member do
        get :favorites
      end
    end
    # ハッシュ
    get '/post_images/hashtag/:name' => 'post_images#hashtag'

    resources :post_images, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get :following_posts
        get :popular
      end
    end
  end

end

app/views/layouts/_error.html.erb
 <% if object.errors.any? %>
   <ul>
   <%= object.errors.count %>件のエラーが発生しました
     <% object.errors.full_messages.each do |message| %>
       <li>
         <%= message %>
       </li>
     <% end %>
   </ul>
 <% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <p class="alert alert-success"><%= notice %></p>
<% elsif flash[:alert] %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>PlanT-to</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!--ヘッダー-->
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg">
    <!--ロゴ-->
   <div class="container-fluid">

      <a class="navbar-brand" href="/post_images">
        <div>
         <%= image_tag(('title.png'),width: '15%',height: '15%') %>
        </div>
      </a>

      <button class="navbar-dark navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>

      <% unless signed_in? %>
      <% else %>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <ul class="navbar-nav mx-5">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to post_images_path, class: 'nav-link text-light' do %>
                <strong>
                 <i class="fa-solid fa-sun-plant-wilt"></i>Home
                </strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to search_path, class: 'nav-link text-light' do %>
                <strong>
                 <i class="fa-solid fa-magnifying-glass"></i>Search
                </strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_news_images_path, class: 'nav-link text-light' do %>
                <strong>
                 <i class="fa-solid fa-bullhorn"></i>News
                </strong>
              <% end %>
            </li>
          <% else %>
          <!--管理者の場合-->
            <li class="nav-item">
              <%= link_to admin_post_images_path, class: 'nav-link text-light' do %>
                <strong>
                 <i class="fa-solid fa-sun-plant-wilt"></i>Posts
                </strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_users_path, class: 'nav-link text-light' do %>
                <strong>
                 <i class="fa-solid fa-users"></i>Users
                </strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_news_images_path, class: 'nav-link text-light' do %>
                <strong>
                 <i class="fa-solid fa-bullhorn"></i>News
                </strong>
              <% end %>
            </li>
          <% end %>

          <!--アイコン-->
          <li class="dropdown nav-item">
            <!--外側-->
            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton", data-toggle="dropdown">
              <% if user_signed_in? %>
                <!--会員の場合-->
              　<%= image_tag current_user.get_profile_image(100,100),class: "rounded-circle icon" %>
              <% else %>
                <!--管理者の場合-->
              　<%= image_tag 'no-user_image.jpg',width: '30px',height: '30px',class: "rounded-circle" %>
              <% end %>
            </button>
            <!--アイコン中身-->
              <div class="dropdown-menu dropdown-menu-right">
              <% if user_signed_in? %>
              <!--会員の場合-->
                <%= link_to user_path(current_user), class: 'nav-link text-dark' do %>
                 マイページ
                <% end %>
                <%= link_to new_post_image_path, class: 'nav-link text-dark ' do %>
                 投稿
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
                 ログアウト
                <% end %>
              <% else %>
                <!--管理者の場合-->
                <%= link_to new_admin_news_image_path, class: 'nav-link text-dark' do %>
                 投稿
                <% end %>
                <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
                 ログアウト
                <% end %>
              <% end %>
              </div>
          </li>
        </ul>

       </div>
     <% end %>
   </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanT-to(プラントット)</title>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--BootStrap導入によりlink_tag → pack_tag-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--FontAwsome導入-->
    <script src="https://kit.fontawesome.com/3e77649537.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <!--ヘッダー-->
    <% if signed_in? %>
      <%= render 'layouts/header' %>
    <% end %>
    <!--フラッシュメッセージ-->
    <%= render 'layouts/flash' %>
    <!--各ページ-->
    <%= yield %>
    <!--フッター-->
    <% if signed_in? %>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>

</html>